export default function Home({ onGetStarted }) {
  const features = [
    {
      icon: "🧠",
      title: "AI-Powered Explanations",
      desc: "Detailed explanations and key points generated by Groq's Llama3 LLM.",
    },
    {
      icon: "🃏",
      title: "Interactive Flashcards",
      desc: "Flip-card flashcards with questions and answers for active recall.",
    },
    {
      icon: "🖼️",
      title: "Smart Image Gallery",
      desc: "Wikipedia images with AI-generated fallbacks for every flashcard.",
    },
    {
      icon: "🔍",
      title: "Semantic Search",
      desc: "ChromaDB vector store lets you search and revisit past topics.",
    },
  ];

  return (
    <div className="text-center py-10 max-w-4xl mx-auto">
      <div className="mb-8">
        <span className="inline-block bg-blue-100 text-blue-700 text-sm font-semibold px-4 py-1 rounded-full mb-4">
          Powered by Groq · Wikipedia · ChromaDB
        </span>
        <h1 className="text-5xl font-extrabold text-gray-900 mb-4 leading-tight">
          Multimodal <span className="text-blue-600">Education Creator</span>
        </h1>
        <p className="text-xl text-gray-500 max-w-2xl mx-auto">
          Enter any topic and instantly get a structured lesson — explanation, key points, flashcards, and images.
        </p>
      </div>

      <button
        onClick={onGetStarted}
        className="btn-primary text-lg px-10 py-4 mb-14 inline-block"
      >
        Get Started →
      </button>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
        {features.map((f) => (
          <div key={f.title} className="card text-left flex gap-4">
            <span className="text-3xl">{f.icon}</span>
            <div>
              <h3 className="font-bold text-gray-800 text-lg">{f.title}</h3>
              <p className="text-gray-500 mt-1 text-sm">{f.desc}</p>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
